### ISSUE TITLE
making a new post from netlifycms is broken

### ISSUE THREAD

**Issue by sw-yx** [konsumer/gatsby-starter-bootstrap-netlify#2] opened 2017-12-22 04:54 UTC
hey, nice template, however it didnt work for me.

first of all it marks the attachment and the related posts as required in the admin. this is probably wrong:

![image](https://user-images.githubusercontent.com/6764957/34285766-33fef4fa-e717-11e7-8b0b-f0806675948b.png)

then when you save the post, gatsby just dies and doesnt publish:

```
12:51:17 PM: Build ready to start
12:51:17 PM: Fetching cached dependencies
12:51:18 PM: Starting to download cache of 123.9MB
12:51:19 PM: Finished downloading cache in 851.220519ms
12:51:25 PM: Preparing Git Reference refs/heads/master
12:51:26 PM: Running build command: gatsby build
12:51:29 PM: v6.12.2 is already installed.
12:51:30 PM: Now using node v6.12.2 (npm v3.10.10)
12:51:30 PM: Using version v6.12.2 of node
12:51:30 PM: Using /opt/buildhome/.rvm/gems/ruby-2.1.2
12:51:31 PM: Installing NPM modules using Yarn version 0.18.1
12:51:32 PM: yarn install v0.18.1
12:51:32 PM: [1/4] Resolving packages...
12:51:33 PM: success Already up-to-date.
12:51:33 PM: Done in 1.24s.
12:51:33 PM: NPM modules installed using Yarn
12:51:35 PM: success delete html files from previous builds — 0.016 s
12:51:35 PM: success open and validate gatsby-config.js — 0.020 s
12:51:35 PM: success copy gatsby files — 0.028 s
12:51:35 PM: success onPreBootstrap — 0.009 s
12:51:35 PM: success source and transform nodes — 0.158 s
12:51:36 PM: success building schema — 0.426 s
12:51:36 PM: success createLayouts — 0.011 s
12:51:36 PM: success createPages — 0.160 s
12:51:36 PM: success createPagesStatefully — 0.018 s
12:51:36 PM: success onPreExtractQueries — 0.001 s
12:51:36 PM: success update schema — 0.228 s
12:51:36 PM: success extract queries from components — 0.203 s
12:51:37 PM: success run graphql queries — 0.091 s
12:51:37 PM: success write out page data — 0.004 s
12:51:37 PM: success write out redirect data — 0.001 s
12:51:37 PM: success onPostBootstrap — 0.001 s
12:51:37 PM: 
12:51:37 PM: info bootstrap finished - 3.391 s
12:51:44 PM: success Building CSS — 7.430 s
12:52:13 PM: success Building production JavaScript bundles — 29.262 s
12:52:19 PM: 
12:52:19 PM: error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND
12:52:19 PM: 
  14 | export default function Template ({ data }) {
  15 |   const { markdownRemark: post } = data
> 16 |   const related = post.frontmatter.related ? post.frontmatter.related.map(r => findNode(r.post, data)) : []
     |                        ^
  17 |   return (
  18 |     <div>
  19 |       <Helmet title={`Blog | ${post.frontmatter.title}`}>


  WebpackError: Cannot read property 'frontmatter' of null
  
  - blog.js:16 Template
    src/templates/blog.js:16:24
  
  - ReactCompositeComponent.js:306 ReactCompositeComponentWrapper._constructComp    onentWithoutOwner
    ~/react-dom/lib/ReactCompositeComponent.js:306:1
  
  - ReactCompositeComponent.js:282 ReactCompositeComponentWrapper._constructComp    onent
    ~/react-dom/lib/ReactCompositeComponent.js:282:1
  
  - ReactCompositeComponent.js:185 ReactCompositeComponentWrapper.mountComponent    ~/react-dom/lib/ReactCompositeComponent.js:185:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1
  
  - ReactDOMComponent.js:657 ReactDOMComponent._createContentMarkup
    ~/react-dom/lib/ReactDOMComponent.js:657:1
  
  - ReactDOMComponent.js:524 ReactDOMComponent.mountComponent
    ~/react-dom/lib/ReactDOMComponent.js:524:1
  
  - ReactReconciler.js:43 Object.mountComponent
    ~/react-dom/lib/ReactReconciler.js:43:1
  
  - ReactMultiChild.js:234 ReactDOMComponent.mountChildren
    ~/react-dom/lib/ReactMultiChild.js:234:1
  
12:52:19 PM: Cached NPM modules
12:52:19 PM: Saved Yarn cache
12:52:19 PM: Build complete: exit code: 1
12:52:19 PM: Saved Cache Directory
12:52:19 PM: Cleaning up docker container
12:52:19 PM: Error running command: Build script returned non-zero exit code: 1
12:52:20 PM: An error occurred while building the site, skipping the deploy and cache refresh.
12:52:20 PM: Build script returned non-zero exit code: 1
12:52:22 PM: Finished processing build request in 1m4.761833045s
```

sorry.

**Comment by konsumer** [comment] 2017-12-22 08:27
Hmm, I get this if I don't have any markdown posts. Do you have some demo.posts? Can you link to a repo of your code? I can take a look.

**Comment by konsumer** [comment] 2018-03-11 21:57
@sw-yx did you get it working? again, if you link to your code, I can take a look.

**Comment by matthewrobb** [comment] 2018-03-21 21:49
I am still seeing this issue :/

**Comment by konsumer** [comment] 2018-03-21 22:12
I am not, so I'm happy to troubleshoot if you can provide a reproduction of the issue, and more information about your environment, but otherwise, I'm not sure what the issue might be.

Here is an asciinema of it working for me:

[![asciicast](https://asciinema.org/a/54gSWfut3eLRHICVajHvVh7Ym.png)](https://asciinema.org/a/54gSWfut3eLRHICVajHvVh7Ym)

**Comment by konsumer** [comment] 2018-03-21 22:19
Like the error above is literally saying "I found a post, but it's null, so I can't mess with it's frontmatter". This could be caused by a lot of things, but most likely cause, without anymore info, is there are missing post files (user-error.) I am happy to help if you can point me to a github of a project that fails.

**Comment by konsumer** [comment] 2018-03-21 22:21
A 2-second 1-line guard could probly fix it (the fact that there are no post files for it to index) but I'd rather see a "broken" example, before I write the code.

**Comment by matthewrobb** [comment] 2018-03-21 22:44
```
5:50:18 PM: The GraphQL query from /opt/build/repo/src/templates/blog.js failed
5:50:18 PM:         Errors:
5:50:18 PM:           GraphQLError: Cannot read property 'id' of undefined
5:50:18 PM:         Query:
5:50:18 PM:           query BlogPostByPath(
5:50:18 PM:   $path: String!
5:50:18 PM: ) {
5:50:18 PM:   site {
5:50:18 PM:     siteMetadata {
5:50:18 PM:       disqus
5:50:18 PM:     }
5:50:18 PM:   }
5:50:18 PM:   markdownRemark(frontmatter: {path: {eq: $path}}) {
5:50:18 PM:     html
5:50:18 PM:     frontmatter {
5:50:18 PM:       path
5:50:18 PM:       date(formatString: "MMMM DD, YYYY")
5:50:18 PM:       title
5:50:18 PM:       attachments {
5:50:18 PM:         filename
5:50:18 PM:       }
5:50:18 PM:       related {
5:50:18 PM:         post
5:50:18 PM:       }
5:50:18 PM:     }
5:50:18 PM:   }
5:50:18 PM:   allMarkdownRemark {
5:50:19 PM:     edges {
5:50:19 PM:       node {
5:50:19 PM:         frontmatter {
5:50:19 PM:           title
5:50:19 PM:           path
5:50:19 PM:         }
5:50:19 PM:       }
5:50:19 PM:     }
5:50:19 PM:   }
5:50:19 PM: }
```

**Comment by konsumer** [comment] 2018-03-21 23:00
Thanks. I will take a look at your project. The main thing to keep in mind is it's not really netlify that does anything, other than triggering build (and providing auth & file-api to netlify-cms.) Changes to config.yml shouldn't affect how it builds, but the generated files might not be kosher with gatsby/this project, which will make the build fail. I am happy to make the templates & gatsby stuff ignore bad files, but "bad files" can mean a lot of different things.

Here is me installing & building yours:
[![asciicast](https://asciinema.org/a/uonRqe5ShJrg3F8p0b4nPy13f.png)](https://asciinema.org/a/uonRqe5ShJrg3F8p0b4nPy13f)

I get error:

```
error Unable to find plugin "gatsby-plugin-netlify-cms"
```

Since this isn't in my [gatsby-config.js](https://github.com/konsumer/gatsby-starter-bootstrap-netlify/blob/master/gatsby-config.js), I'm not sure what to think other than you must have edited it some other ways. 

I removed that line, and tried again, and got this error:

```
```

**Comment by matthewrobb** [comment] 2018-03-21 23:03
I'm sorry that repo is stale from my local other than content files.... I am just jumping into this whole gatsby/netlify/static site gen world.

Looking at the md files you bundled vs the ones netlify cms is producing it looks as though the date: header field is quoted in the generated file but not in the ones in the starter repo. Not sure if this helps at all.

**Comment by konsumer** [comment] 2018-03-21 23:07
no prob. I hit "Comment" button too fast, updated my reply.

**Comment by matthewrobb** [comment] 2018-03-21 23:07
I almost feel as though it's an issue with the list widget in the schema. The files in this repo contain ```attachments: []``` but if I make attachments ```required: false``` and then create a post it just omits the field

**Comment by konsumer** [comment] 2018-03-21 23:08
Agreed, and that's out of my control, really.

**Comment by konsumer** [comment] 2018-03-21 23:10
it's like a mix of 2 things:

* gatsby dynamically adds fields to graphql-queryable object, based on what's there. This is super-handy (you can just add stuff to the frontmatter, and then query it) but if no content has the field, there isn't a simple way to make it available to a query
* netlify-cms `required` leaves the field out if you don't set anything.

**Comment by matthewrobb** [comment] 2018-03-21 23:12
What would be nice is if the validation didn't fail on an empty list or if you could do `default: []`

**Comment by konsumer** [comment] 2018-03-21 23:14
it might be silly, but like an "example" set of content-types, that are marked hidden might be the trick. like a dummy blog post, about-page, etc, that has all the fields. on list, leave it out, but when gatsby is trying to work out what fields to look at, it will take it into consideration.

**Comment by konsumer** [comment] 2018-03-21 23:30
Actually, just did that, and it worked. I should add that to the template-project. I kind of like that it also documents how to make a thing. I will re-open the issue until I get it in there, but in the meantime, [here](https://github.com/konsumer/kj-home-on-the-mend) is your project, all fixed.

**Comment by konsumer** [comment] 2018-03-21 23:31
the main difference is that I added a file indexer for src/examples, ignored "hidden" files in index, and added some example-files.

**Comment by matthewrobb** [comment] 2018-03-21 23:32
You might want to go a step further as I am doing locally now and create essentially 2 stub files that reference each other where needed but also are marked hidden (I am trying to work this out now) and thus excluded from content lists and searches. The idea would be the stub posts should always flex the full capabilities of the content type.

**Comment by konsumer** [comment] 2018-03-21 23:33
That is what I did.

**Comment by matthewrobb** [comment] 2018-03-21 23:34
Yeah we're right on top of each other atm haha sorry.

**Comment by konsumer** [comment] 2018-03-21 23:37
See [here](https://github.com/konsumer/kj-home-on-the-mend/blob/master/src/examples/blog.md) which fleshes out all the fields. You could basically do this with any content-type/fields, and then later check for `hidden`. A second-part fo this trick is that the examples are in another directory, so netlify-cms won't list them in "Blog", and they just act as a definition/docs for making new content. I think this will also make it so I can remove the dumb demo posts & images, and people can just explore the content-types by adding their own content.

**Comment by konsumer** [comment] 2018-03-22 00:36
Ok, changes are checked in, so new blogs made with this template will use the examples files. I also added greenkeeper & travis to keep the repo in good health.

**Comment by konsumer** [comment] 2018-03-22 00:36
closing for now, but feel free to make more comments if the issue pops up, again.

**Closed by konsumer** 2018-03-22 00:36 UTC

**Comment by matthewrobb** [comment] 2018-03-25 23:34
@konsumer Just wanted to let you know that I updated quite a few dependencies so I am not sure exactly what solved the initial problem but I am now able to keep those list widget fields as required but specifying ```default: []``` and have it correctly output into the frontmatter.

**Comment by sw-yx** [comment] 2018-03-26 00:21
eeps sorry for the driveby Issue report David Ive been slacking on my github notifications. I dont use this starter anymore so I cant really provide anymore input. sorry i didnt respond sooner!
